spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_management_v01
    username: springuser
    password: springpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  #
    show-sql: true
    properties:
      hibernate:
        format_sql: true
